# Generated by Django 5.1.5 on 2025-05-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAGQABot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragqa',
            name='userid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
