# Generated by Django 5.1.5 on 2025-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAGQABot', '0002_ragqa_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragqa',
            name='documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
